trainer: renderer_trainer

max_iter: 1000000
epoch_iter: 10000
eval_iter:  50000
save_iter: 200000
vis_iter:  100000
ckpt_select_metric:
  name: perc_loss
  type: min

optimizer:
  renderer:
    name: adam
    args: {lr: 3.6e-5, betas: [0.5, 0.9]}
  disc:
    name: adam
    args: {lr: 3.6e-5, betas: [0.5, 0.9]}

gan_start_after_iters: 0
find_unused_parameters: true

visualize:
  resolution: 256
  ds_samples: 16
  ae_center_zoom_res: 1024