datasets:
  train:
    name: odisr-liif
    args:
      dataset:
        name: image_folder
        args: {root_path: ../data/lau_dataset/odisr/training/HR}
<<<<<<< HEAD
      lr_inp_size: (512, 1024)
      hr_tgt_size: (4096, 8192)
      gt_crop_size: (64, 64)
      gt_size_min: (1024, 2048)
      gt_size_max: (4096, 8192)
=======
      lr_inp_size: [512, 1024]
      hr_tgt_size: [2048, 4096]
      gt_crop_size: [48, 48]
      gt_size_min: [1024, 2048]
      gt_size_max: [2048, 4096]
>>>>>>> origin/master

  val:
    name: odisr-liif
    args:
      dataset:
        name: image_folder
        args: {root_path: ../data/lau_dataset/odisr/validation/HR}
<<<<<<< HEAD
      lr_inp_size: (512, 1024)
      hr_tgt_size: (4096, 8192)
      gt_crop_size: (64, 64)
      gt_size_min: (1024, 2048)
      gt_size_max: (4096, 8192)
=======
      lr_inp_size: [512, 1024]
      hr_tgt_size: [2048, 4096]
      gt_crop_size: [48, 48]
      gt_size_min: [1024, 2048]
      gt_size_max: [2048, 4096]
>>>>>>> origin/master
